name: Shell Script Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**/*.sh'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**/*.sh'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          echo "Running ShellCheck on all shell scripts..."
          find src -name "*.sh" -type f -print0 | xargs -0 shellcheck -x

  test-scripts:
    name: Test Shell Scripts
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set execute permissions
        run: |
          chmod +x src/*.sh
          find src -name "*.sh" -type f -exec chmod +x {} \;

      - name: Test NHL download script (help mode)
        run: |
          ./src/download_nhl.sh --help || echo "Help command returned non-zero exit code: $?"

      - name: Test WHL download script (help mode)
        run: |
          ./src/download_whl.sh --help || echo "Help command returned non-zero exit code: $?"

      - name: Test WHL playoff download script (help mode)
        run: |
          ./src/download_whl_playoff_game.sh --help || echo "Help command returned non-zero exit code: $?"

      - name: Debug information
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          echo "Debug information:"
          echo "Shell version: $SHELL --version"
          echo "Available scripts:"
          find src -name "*.sh" -type f | sort
